added deployment

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -1,4 +1,4 @@
-name: CD - GitHub Docker Packages & Render
+name: CD - GitHub Docker Packages & Deploy Render
 on:
   push:
     branches: [master]
@@ -41,3 +41,10 @@ jobs:
         run: |
           docker push $REGISTRY/$REPOSITORY:$VERSION
           docker push $REGISTRY/$REPOSITORY:latest
+      - name: Deploy on Render
+        # En Render, en el servicio Web, Settings >> Deploy Hook >>  copiar el token de acceso
+        # En GitHub, en el repositorio, Settings >> Secrets and variables >> Actions >> definir la variable de entorno
+        # DEPLOY_HOOK_TOKEN con el token
+        run: |
+          curl --fail -X POST "https://api.render.com/deploy/${{ secrets.DEPLOY_HOOK_TOKEN }}" || { echo "Deployment failed"; exit 1; }
+          echo "Deployment succeeded"
